name: 🧼 PR

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  auto-assign:
    name: Auto-assign author
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: toshimaru/auto-author-assign@3e19bfc990cb1cf0589dce95e9f75289bb1e22de
