// Code generated by map-generator; DO NOT EDIT.
// Map metadata lives in map-generator/assets/maps/<map>/info.json.
// Regenerate with `npm run gen-maps`.

export enum GameMapType {
  Achiran = "Achiran", // map-generator/assets/maps/achiran/info.json
  Aegean = "Aegean", // map-generator/assets/maps/aegean/info.json
  Africa = "Africa", // map-generator/assets/maps/africa/info.json
  Alps = "Alps", // map-generator/assets/maps/alps/info.json
  AmazonRiver = "Amazon River", // map-generator/assets/maps/amazonriver/info.json
  Antarctica = "Antarctica", // map-generator/assets/maps/antarctica/info.json
  ArchipelagoSea = "ArchipelagoSea", // map-generator/assets/maps/archipelagosea/info.json
  Arctic = "Arctic", // map-generator/assets/maps/arctic/info.json
  Asia = "Asia", // map-generator/assets/maps/asia/info.json
  Australia = "Australia", // map-generator/assets/maps/australia/info.json
  Baikal = "Baikal", // map-generator/assets/maps/baikal/info.json
  BaikalNukeWars = "Baikal Nuke Wars", // map-generator/assets/maps/baikalnukewars/info.json
  BajaCalifornia = "Baja California", // map-generator/assets/maps/bajacalifornia/info.json
  Balkans = "Balkans", // map-generator/assets/maps/balkans/info.json
  BeringSea = "Bering Sea", // map-generator/assets/maps/beringsea/info.json
  BeringStrait = "Bering Strait", // map-generator/assets/maps/beringstrait/info.json
  BetweenTwoSeas = "Between Two Seas", // map-generator/assets/maps/betweentwoseas/info.json
  BlackSea = "Black Sea", // map-generator/assets/maps/blacksea/info.json
  BosphorusStraits = "Bosphorus Straits", // map-generator/assets/maps/bosphorusstraits/info.json
  Britannia = "Britannia", // map-generator/assets/maps/britannia/info.json
  BritanniaClassic = "Britannia Classic", // map-generator/assets/maps/britanniaclassic/info.json
  Caribbean = "Caribbean", // map-generator/assets/maps/caribbean/info.json
  Caucasus = "Caucasus", // map-generator/assets/maps/caucasus/info.json
  ChoppingBlock = "Chopping Block", // map-generator/assets/maps/choppingblock/info.json
  Conakry = "Conakry", // map-generator/assets/maps/conakry/info.json
  DanishStraits = "Danish Straits", // map-generator/assets/maps/danishstraits/info.json
  DeglaciatedAntarctica = "Deglaciated Antarctica", // map-generator/assets/maps/deglaciatedantarctica/info.json
  Didier = "Didier", // map-generator/assets/maps/didier/info.json
  DidierFrance = "Didier France", // map-generator/assets/maps/didierfrance/info.json
  Dyslexdria = "Dyslexdria", // map-generator/assets/maps/dyslexdria/info.json
  EastAsia = "East Asia", // map-generator/assets/maps/eastasia/info.json
  Europe = "Europe", // map-generator/assets/maps/europe/info.json
  EuropeClassic = "Europe Classic", // map-generator/assets/maps/europeclassic/info.json
  FalklandIslands = "Falkland Islands", // map-generator/assets/maps/falklandislands/info.json
  FaroeIslands = "Faroe Islands", // map-generator/assets/maps/faroeislands/info.json
  FourIslands = "Four Islands", // map-generator/assets/maps/fourislands/info.json
  GatewayToTheAtlantic = "Gateway to the Atlantic", // map-generator/assets/maps/gatewaytotheatlantic/info.json
  GiantWorldMap = "Giant World Map", // map-generator/assets/maps/giantworldmap/info.json
  GreatLakes = "Great Lakes", // map-generator/assets/maps/greatlakes/info.json
  GulfOfStLawrence = "Gulf of St. Lawrence", // map-generator/assets/maps/gulfofstlawrence/info.json
  Halkidiki = "Halkidiki", // map-generator/assets/maps/halkidiki/info.json
  Hawaii = "Hawaii", // map-generator/assets/maps/hawaii/info.json
  HongKong = "Hong Kong", // map-generator/assets/maps/hongkong/info.json
  Iceland = "Iceland", // map-generator/assets/maps/iceland/info.json
  IndianSubcontinent = "Indian Subcontinent", // map-generator/assets/maps/indiansubcontinent/info.json
  Italia = "Italia", // map-generator/assets/maps/italia/info.json
  Japan = "Japan", // map-generator/assets/maps/japan/info.json
  JuanDeFucaStrait = "Juan De Fuca Strait", // map-generator/assets/maps/juandefucastrait/info.json
  Korea = "Korea", // map-generator/assets/maps/korea/info.json
  Labyrinth = "Labyrinth", // map-generator/assets/maps/labyrinth/info.json
  Lemnos = "Lemnos", // map-generator/assets/maps/lemnos/info.json
  Lisbon = "Lisbon", // map-generator/assets/maps/lisbon/info.json
  LosAngeles = "Los Angeles", // map-generator/assets/maps/losangeles/info.json
  Luna = "Luna", // map-generator/assets/maps/luna/info.json
  Manicouagan = "Manicouagan", // map-generator/assets/maps/manicouagan/info.json
  MareNostrum = "Mare Nostrum", // map-generator/assets/maps/marenostrum/info.json
  Mars = "Mars", // map-generator/assets/maps/mars/info.json
  Mena = "Mena", // map-generator/assets/maps/mena/info.json
  MiddleEast = "Middle East", // map-generator/assets/maps/middleeast/info.json
  MilkyWay = "MilkyWay", // map-generator/assets/maps/milkyway/info.json
  MississippiRiver = "Mississippi River", // map-generator/assets/maps/mississippiriver/info.json
  Montreal = "Montreal", // map-generator/assets/maps/montreal/info.json
  NewYorkCity = "New York City", // map-generator/assets/maps/newyorkcity/info.json
  NileDelta = "Nile Delta", // map-generator/assets/maps/niledelta/info.json
  NorthAmerica = "North America", // map-generator/assets/maps/northamerica/info.json
  NorthwestPassage = "Northwest Passage", // map-generator/assets/maps/northwestpassage/info.json
  Oceania = "Oceania", // map-generator/assets/maps/oceania/info.json
  Onion = "Onion", // map-generator/assets/maps/onion/info.json
  Pangaea = "Pangaea", // map-generator/assets/maps/pangaea/info.json
  Passage = "Passage", // map-generator/assets/maps/passage/info.json
  Pluto = "Pluto", // map-generator/assets/maps/pluto/info.json
  SanFrancisco = "San Francisco", // map-generator/assets/maps/sanfrancisco/info.json
  Sierpinski = "Sierpinski", // map-generator/assets/maps/sierpinski/info.json
  SouthAmerica = "South America", // map-generator/assets/maps/southamerica/info.json
  SoutheastAsia = "SoutheastAsia", // map-generator/assets/maps/southeastasia/info.json
  StraitOfGibraltar = "Strait of Gibraltar", // map-generator/assets/maps/straitofgibraltar/info.json
  StraitOfHormuz = "Strait of Hormuz", // map-generator/assets/maps/straitofhormuz/info.json
  StraitOfMalacca = "Strait Of Malacca", // map-generator/assets/maps/straitofmalacca/info.json
  Surrounded = "Surrounded", // map-generator/assets/maps/surrounded/info.json
  Svalmel = "Svalmel", // map-generator/assets/maps/svalmel/info.json
  TaiwanStrait = "Taiwan Strait", // map-generator/assets/maps/taiwanstrait/info.json
  TheBox = "The Box", // map-generator/assets/maps/thebox/info.json
  Titan = "Titan", // map-generator/assets/maps/titan/info.json
  Tourney1 = "Tourney 2 Teams", // map-generator/assets/maps/tourney1/info.json
  Tourney2 = "Tourney 3 Teams", // map-generator/assets/maps/tourney2/info.json
  Tourney3 = "Tourney 4 Teams", // map-generator/assets/maps/tourney3/info.json
  Tourney4 = "Tourney 8 Teams", // map-generator/assets/maps/tourney4/info.json
  TradersDream = "Traders Dream", // map-generator/assets/maps/tradersdream/info.json
  TwoLakes = "Two Lakes", // map-generator/assets/maps/twolakes/info.json
  Venice = "Venice", // map-generator/assets/maps/venice/info.json
  WarshipWarship = "Warship Warship", // map-generator/assets/maps/warshipwarship/info.json
  World = "World", // map-generator/assets/maps/world/info.json
  WorldInverted = "World Inverted", // map-generator/assets/maps/worldinverted/info.json
  YellowSea = "Yellow Sea", // map-generator/assets/maps/yellowsea/info.json
  Yenisei = "Yenisei", // map-generator/assets/maps/yenisei/info.json
}

export type GameMapName = keyof typeof GameMapType;

export type MapCategory =
  | "featured"
  | "new"
  | "world"
  | "continental"
  | "europe"
  | "asia"
  | "north_america"
  | "africa"
  | "south_america"
  | "oceania"
  | "antarctica"
  | "cosmic"
  | "fictional"
  | "arcade"
  | "tournament";

// Category display order in the map picker.
export const mapCategoryOrder: readonly MapCategory[] = [
  "featured",
  "new",
  "world",
  "continental",
  "europe",
  "asia",
  "north_america",
  "africa",
  "south_america",
  "oceania",
  "antarctica",
  "cosmic",
  "fictional",
  "arcade",
  "tournament",
];

export interface MapInfo {
  /** GameMapType enum key — the UpperCamelCase folder name. */
  id: GameMapName;
  /** Canonical map name (wire format) — the GameMapType enum value. */
  type: GameMapType;
  /** Key of the map's display name in resources/lang/en.json. */
  translationKey: string;
  /** Map picker categories. */
  categories: MapCategory[];
  /** How many times the map appears in the multiplayer playlist. */
  multiplayerFrequency: number;
  /** Position in the featured grid (1 = first); unranked featured maps sort last. */
  featuredRank?: number;
  /** Preferred team count in team/special games (see MapPlaylist). */
  specialTeamCount?: number;
}

export const maps: readonly MapInfo[] = [
  {
    id: "Achiran",
    type: GameMapType.Achiran,
    translationKey: "map.achiran",
    categories: ["fictional", "europe"],
    multiplayerFrequency: 5,
  },
  {
    id: "Aegean",
    type: GameMapType.Aegean,
    translationKey: "map.aegean",
    categories: ["europe", "asia"],
    multiplayerFrequency: 6,
    specialTeamCount: 2,
  },
  {
    id: "Africa",
    type: GameMapType.Africa,
    translationKey: "map.africa",
    categories: ["featured", "continental", "africa"],
    multiplayerFrequency: 7,
    featuredRank: 6,
  },
  {
    id: "Alps",
    type: GameMapType.Alps,
    translationKey: "map.alps",
    categories: ["europe"],
    multiplayerFrequency: 4,
  },
  {
    id: "AmazonRiver",
    type: GameMapType.AmazonRiver,
    translationKey: "map.amazonriver",
    categories: ["south_america"],
    multiplayerFrequency: 3,
  },
  {
    id: "Antarctica",
    type: GameMapType.Antarctica,
    translationKey: "map.antarctica",
    categories: ["antarctica", "continental"],
    multiplayerFrequency: 1,
  },
  {
    id: "ArchipelagoSea",
    type: GameMapType.ArchipelagoSea,
    translationKey: "map.archipelagosea",
    categories: ["europe"],
    multiplayerFrequency: 3,
  },
  {
    id: "Arctic",
    type: GameMapType.Arctic,
    translationKey: "map.arctic",
    categories: ["europe", "north_america", "asia"],
    multiplayerFrequency: 6,
  },
  {
    id: "Asia",
    type: GameMapType.Asia,
    translationKey: "map.asia",
    categories: ["featured", "continental", "asia"],
    multiplayerFrequency: 6,
    featuredRank: 5,
  },
  {
    id: "Australia",
    type: GameMapType.Australia,
    translationKey: "map.australia",
    categories: ["oceania"],
    multiplayerFrequency: 4,
  },
  {
    id: "Baikal",
    type: GameMapType.Baikal,
    translationKey: "map.baikal",
    categories: ["asia"],
    multiplayerFrequency: 5,
    specialTeamCount: 2,
  },
  {
    id: "BaikalNukeWars",
    type: GameMapType.BaikalNukeWars,
    translationKey: "map.baikalnukewars",
    categories: ["fictional"],
    multiplayerFrequency: 0,
  },
  {
    id: "BajaCalifornia",
    type: GameMapType.BajaCalifornia,
    translationKey: "map.bajacalifornia",
    categories: ["north_america"],
    multiplayerFrequency: 4,
  },
  {
    id: "Balkans",
    type: GameMapType.Balkans,
    translationKey: "map.balkans",
    categories: ["europe"],
    multiplayerFrequency: 6,
  },
  {
    id: "BeringSea",
    type: GameMapType.BeringSea,
    translationKey: "map.beringsea",
    categories: ["asia", "north_america"],
    multiplayerFrequency: 5,
    specialTeamCount: 2,
  },
  {
    id: "BeringStrait",
    type: GameMapType.BeringStrait,
    translationKey: "map.beringstrait",
    categories: ["asia", "north_america"],
    multiplayerFrequency: 2,
    specialTeamCount: 2,
  },
  {
    id: "BetweenTwoSeas",
    type: GameMapType.BetweenTwoSeas,
    translationKey: "map.betweentwoseas",
    categories: ["europe", "asia"],
    multiplayerFrequency: 5,
  },
  {
    id: "BlackSea",
    type: GameMapType.BlackSea,
    translationKey: "map.blacksea",
    categories: ["europe", "asia"],
    multiplayerFrequency: 6,
  },
  {
    id: "BosphorusStraits",
    type: GameMapType.BosphorusStraits,
    translationKey: "map.bosphorusstraits",
    categories: ["europe", "asia"],
    multiplayerFrequency: 3,
    specialTeamCount: 2,
  },
  {
    id: "Britannia",
    type: GameMapType.Britannia,
    translationKey: "map.britannia",
    categories: ["europe"],
    multiplayerFrequency: 5,
  },
  {
    id: "BritanniaClassic",
    type: GameMapType.BritanniaClassic,
    translationKey: "map.britanniaclassic",
    categories: ["europe"],
    multiplayerFrequency: 0,
  },
  {
    id: "Caribbean",
    type: GameMapType.Caribbean,
    translationKey: "map.caribbean",
    categories: ["north_america"],
    multiplayerFrequency: 5,
  },
  {
    id: "Caucasus",
    type: GameMapType.Caucasus,
    translationKey: "map.caucasus",
    categories: ["europe", "asia"],
    multiplayerFrequency: 5,
  },
  {
    id: "ChoppingBlock",
    type: GameMapType.ChoppingBlock,
    translationKey: "map.choppingblock",
    categories: ["arcade"],
    multiplayerFrequency: 5,
    specialTeamCount: 4,
  },
  {
    id: "Conakry",
    type: GameMapType.Conakry,
    translationKey: "map.conakry",
    categories: ["africa"],
    multiplayerFrequency: 3,
    specialTeamCount: 2,
  },
  {
    id: "DanishStraits",
    type: GameMapType.DanishStraits,
    translationKey: "map.danishstraits",
    categories: ["europe"],
    multiplayerFrequency: 5,
  },
  {
    id: "DeglaciatedAntarctica",
    type: GameMapType.DeglaciatedAntarctica,
    translationKey: "map.deglaciatedantarctica",
    categories: ["antarctica", "fictional"],
    multiplayerFrequency: 4,
  },
  {
    id: "Didier",
    type: GameMapType.Didier,
    translationKey: "map.didier",
    categories: ["arcade"],
    multiplayerFrequency: 1,
  },
  {
    id: "DidierFrance",
    type: GameMapType.DidierFrance,
    translationKey: "map.didierfrance",
    categories: ["arcade"],
    multiplayerFrequency: 1,
  },
  {
    id: "Dyslexdria",
    type: GameMapType.Dyslexdria,
    translationKey: "map.dyslexdria",
    categories: ["world", "fictional"],
    multiplayerFrequency: 8,
  },
  {
    id: "EastAsia",
    type: GameMapType.EastAsia,
    translationKey: "map.eastasia",
    categories: ["asia"],
    multiplayerFrequency: 5,
  },
  {
    id: "Europe",
    type: GameMapType.Europe,
    translationKey: "map.europe",
    categories: ["featured", "continental", "europe"],
    multiplayerFrequency: 7,
    featuredRank: 2,
  },
  {
    id: "EuropeClassic",
    type: GameMapType.EuropeClassic,
    translationKey: "map.europeclassic",
    categories: ["europe", "continental"],
    multiplayerFrequency: 0,
  },
  {
    id: "FalklandIslands",
    type: GameMapType.FalklandIslands,
    translationKey: "map.falklandislands",
    categories: ["south_america"],
    multiplayerFrequency: 4,
    specialTeamCount: 2,
  },
  {
    id: "FaroeIslands",
    type: GameMapType.FaroeIslands,
    translationKey: "map.faroeislands",
    categories: ["europe"],
    multiplayerFrequency: 4,
  },
  {
    id: "FourIslands",
    type: GameMapType.FourIslands,
    translationKey: "map.fourislands",
    categories: ["fictional"],
    multiplayerFrequency: 4,
    specialTeamCount: 4,
  },
  {
    id: "GatewayToTheAtlantic",
    type: GameMapType.GatewayToTheAtlantic,
    translationKey: "map.gatewaytotheatlantic",
    categories: ["europe"],
    multiplayerFrequency: 5,
  },
  {
    id: "GiantWorldMap",
    type: GameMapType.GiantWorldMap,
    translationKey: "map.giantworldmap",
    categories: ["world"],
    multiplayerFrequency: 10,
  },
  {
    id: "GreatLakes",
    type: GameMapType.GreatLakes,
    translationKey: "map.greatlakes",
    categories: ["north_america"],
    multiplayerFrequency: 6,
  },
  {
    id: "GulfOfStLawrence",
    type: GameMapType.GulfOfStLawrence,
    translationKey: "map.gulfofstlawrence",
    categories: ["north_america"],
    multiplayerFrequency: 4,
    specialTeamCount: 3,
  },
  {
    id: "Halkidiki",
    type: GameMapType.Halkidiki,
    translationKey: "map.halkidiki",
    categories: ["europe"],
    multiplayerFrequency: 4,
  },
  {
    id: "Hawaii",
    type: GameMapType.Hawaii,
    translationKey: "map.hawaii",
    categories: ["oceania"],
    multiplayerFrequency: 4,
  },
  {
    id: "HongKong",
    type: GameMapType.HongKong,
    translationKey: "map.hongkong",
    categories: ["asia"],
    multiplayerFrequency: 6,
  },
  {
    id: "Iceland",
    type: GameMapType.Iceland,
    translationKey: "map.iceland",
    categories: ["europe"],
    multiplayerFrequency: 4,
  },
  {
    id: "IndianSubcontinent",
    type: GameMapType.IndianSubcontinent,
    translationKey: "map.indiansubcontinent",
    categories: ["asia"],
    multiplayerFrequency: 8,
  },
  {
    id: "Italia",
    type: GameMapType.Italia,
    translationKey: "map.italia",
    categories: ["europe"],
    multiplayerFrequency: 6,
  },
  {
    id: "Japan",
    type: GameMapType.Japan,
    translationKey: "map.japan",
    categories: ["featured", "asia"],
    multiplayerFrequency: 6,
    featuredRank: 7,
  },
  {
    id: "JuanDeFucaStrait",
    type: GameMapType.JuanDeFucaStrait,
    translationKey: "map.juandefucastrait",
    categories: ["north_america"],
    multiplayerFrequency: 4,
    specialTeamCount: 3,
  },
  {
    id: "Korea",
    type: GameMapType.Korea,
    translationKey: "map.korea",
    categories: ["asia"],
    multiplayerFrequency: 5,
  },
  {
    id: "Labyrinth",
    type: GameMapType.Labyrinth,
    translationKey: "map.labyrinth",
    categories: ["arcade"],
    multiplayerFrequency: 6,
  },
  {
    id: "Lemnos",
    type: GameMapType.Lemnos,
    translationKey: "map.lemnos",
    categories: ["europe"],
    multiplayerFrequency: 3,
  },
  {
    id: "Lisbon",
    type: GameMapType.Lisbon,
    translationKey: "map.lisbon",
    categories: ["europe"],
    multiplayerFrequency: 4,
  },
  {
    id: "LosAngeles",
    type: GameMapType.LosAngeles,
    translationKey: "map.losangeles",
    categories: ["north_america"],
    multiplayerFrequency: 8,
  },
  {
    id: "Luna",
    type: GameMapType.Luna,
    translationKey: "map.luna",
    categories: ["cosmic"],
    multiplayerFrequency: 6,
    specialTeamCount: 2,
  },
  {
    id: "Manicouagan",
    type: GameMapType.Manicouagan,
    translationKey: "map.manicouagan",
    categories: ["north_america"],
    multiplayerFrequency: 4,
  },
  {
    id: "MareNostrum",
    type: GameMapType.MareNostrum,
    translationKey: "map.marenostrum",
    categories: ["europe", "asia", "africa"],
    multiplayerFrequency: 6,
  },
  {
    id: "Mars",
    type: GameMapType.Mars,
    translationKey: "map.mars",
    categories: ["cosmic"],
    multiplayerFrequency: 3,
  },
  {
    id: "Mena",
    type: GameMapType.Mena,
    translationKey: "map.mena",
    categories: ["asia", "africa"],
    multiplayerFrequency: 6,
  },
  {
    id: "MiddleEast",
    type: GameMapType.MiddleEast,
    translationKey: "map.middleeast",
    categories: ["asia"],
    multiplayerFrequency: 8,
  },
  {
    id: "MilkyWay",
    type: GameMapType.MilkyWay,
    translationKey: "map.milkyway",
    categories: ["cosmic"],
    multiplayerFrequency: 8,
  },
  {
    id: "MississippiRiver",
    type: GameMapType.MississippiRiver,
    translationKey: "map.mississippiriver",
    categories: ["north_america"],
    multiplayerFrequency: 3,
  },
  {
    id: "Montreal",
    type: GameMapType.Montreal,
    translationKey: "map.montreal",
    categories: ["north_america"],
    multiplayerFrequency: 6,
  },
  {
    id: "NewYorkCity",
    type: GameMapType.NewYorkCity,
    translationKey: "map.newyorkcity",
    categories: ["north_america"],
    multiplayerFrequency: 3,
  },
  {
    id: "NileDelta",
    type: GameMapType.NileDelta,
    translationKey: "map.niledelta",
    categories: ["africa"],
    multiplayerFrequency: 4,
  },
  {
    id: "NorthAmerica",
    type: GameMapType.NorthAmerica,
    translationKey: "map.northamerica",
    categories: ["featured", "continental", "north_america"],
    multiplayerFrequency: 5,
    featuredRank: 3,
  },
  {
    id: "NorthwestPassage",
    type: GameMapType.NorthwestPassage,
    translationKey: "map.northwestpassage",
    categories: ["north_america"],
    multiplayerFrequency: 5,
  },
  {
    id: "Oceania",
    type: GameMapType.Oceania,
    translationKey: "map.oceania",
    categories: ["oceania", "continental"],
    multiplayerFrequency: 0,
  },
  {
    id: "Onion",
    type: GameMapType.Onion,
    translationKey: "map.onion",
    categories: ["arcade"],
    multiplayerFrequency: 2,
  },
  {
    id: "Pangaea",
    type: GameMapType.Pangaea,
    translationKey: "map.pangaea",
    categories: ["fictional"],
    multiplayerFrequency: 5,
  },
  {
    id: "Passage",
    type: GameMapType.Passage,
    translationKey: "map.passage",
    categories: ["fictional"],
    multiplayerFrequency: 4,
  },
  {
    id: "Pluto",
    type: GameMapType.Pluto,
    translationKey: "map.pluto",
    categories: ["cosmic"],
    multiplayerFrequency: 6,
    specialTeamCount: 2,
  },
  {
    id: "SanFrancisco",
    type: GameMapType.SanFrancisco,
    translationKey: "map.sanfrancisco",
    categories: ["north_america"],
    multiplayerFrequency: 3,
  },
  {
    id: "Sierpinski",
    type: GameMapType.Sierpinski,
    translationKey: "map.sierpinski",
    categories: ["arcade"],
    multiplayerFrequency: 10,
  },
  {
    id: "SouthAmerica",
    type: GameMapType.SouthAmerica,
    translationKey: "map.southamerica",
    categories: ["featured", "continental", "south_america"],
    multiplayerFrequency: 5,
    featuredRank: 4,
  },
  {
    id: "SoutheastAsia",
    type: GameMapType.SoutheastAsia,
    translationKey: "map.southeastasia",
    categories: ["asia"],
    multiplayerFrequency: 5,
  },
  {
    id: "StraitOfGibraltar",
    type: GameMapType.StraitOfGibraltar,
    translationKey: "map.straitofgibraltar",
    categories: ["europe", "africa"],
    multiplayerFrequency: 5,
    specialTeamCount: 2,
  },
  {
    id: "StraitOfHormuz",
    type: GameMapType.StraitOfHormuz,
    translationKey: "map.straitofhormuz",
    categories: ["asia"],
    multiplayerFrequency: 4,
    specialTeamCount: 2,
  },
  {
    id: "StraitOfMalacca",
    type: GameMapType.StraitOfMalacca,
    translationKey: "map.straitofmalacca",
    categories: ["asia"],
    multiplayerFrequency: 4,
  },
  {
    id: "Surrounded",
    type: GameMapType.Surrounded,
    translationKey: "map.surrounded",
    categories: ["fictional"],
    multiplayerFrequency: 4,
    specialTeamCount: 4,
  },
  {
    id: "Svalmel",
    type: GameMapType.Svalmel,
    translationKey: "map.svalmel",
    categories: ["fictional", "europe", "north_america"],
    multiplayerFrequency: 8,
  },
  {
    id: "TaiwanStrait",
    type: GameMapType.TaiwanStrait,
    translationKey: "map.taiwanstrait",
    categories: ["asia"],
    multiplayerFrequency: 5,
  },
  {
    id: "TheBox",
    type: GameMapType.TheBox,
    translationKey: "map.thebox",
    categories: ["arcade"],
    multiplayerFrequency: 3,
  },
  {
    id: "Titan",
    type: GameMapType.Titan,
    translationKey: "map.titan",
    categories: ["cosmic"],
    multiplayerFrequency: 3,
  },
  {
    id: "Tourney1",
    type: GameMapType.Tourney1,
    translationKey: "map.tourney1",
    categories: ["tournament"],
    multiplayerFrequency: 0,
  },
  {
    id: "Tourney2",
    type: GameMapType.Tourney2,
    translationKey: "map.tourney2",
    categories: ["tournament"],
    multiplayerFrequency: 0,
  },
  {
    id: "Tourney3",
    type: GameMapType.Tourney3,
    translationKey: "map.tourney3",
    categories: ["tournament"],
    multiplayerFrequency: 0,
  },
  {
    id: "Tourney4",
    type: GameMapType.Tourney4,
    translationKey: "map.tourney4",
    categories: ["tournament"],
    multiplayerFrequency: 0,
  },
  {
    id: "TradersDream",
    type: GameMapType.TradersDream,
    translationKey: "map.tradersdream",
    categories: ["fictional"],
    multiplayerFrequency: 4,
    specialTeamCount: 2,
  },
  {
    id: "TwoLakes",
    type: GameMapType.TwoLakes,
    translationKey: "map.twolakes",
    categories: ["europe"],
    multiplayerFrequency: 6,
  },
  {
    id: "Venice",
    type: GameMapType.Venice,
    translationKey: "map.venice",
    categories: ["europe"],
    multiplayerFrequency: 6,
  },
  {
    id: "WarshipWarship",
    type: GameMapType.WarshipWarship,
    translationKey: "map.warshipwarship",
    categories: ["arcade"],
    multiplayerFrequency: 3,
  },
  {
    id: "World",
    type: GameMapType.World,
    translationKey: "map.world",
    categories: ["featured", "world"],
    multiplayerFrequency: 20,
    featuredRank: 1,
  },
  {
    id: "WorldInverted",
    type: GameMapType.WorldInverted,
    translationKey: "map.worldinverted",
    categories: ["world", "fictional"],
    multiplayerFrequency: 8,
  },
  {
    id: "YellowSea",
    type: GameMapType.YellowSea,
    translationKey: "map.yellowsea",
    categories: ["asia"],
    multiplayerFrequency: 5,
  },
  {
    id: "Yenisei",
    type: GameMapType.Yenisei,
    translationKey: "map.yenisei",
    categories: ["asia"],
    multiplayerFrequency: 6,
  },
];
